# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: |
          sudo add-apt-repository ppa:morphis/anbox-support
          sudo apt update
          sudo apt-get install -y anbox-modules-dkms anbox adb
          export DISPLAY=:0
          anbox.appmgr
          adb devices

workflows:
  build:
    jobs:
      - build-medium