version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- restore_cache:
     #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#     - run:
      - run:
          name: Run tests
          command: adb devices

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 3 * * *"
    jobs:
      - build
