version: 2.1
orbs:
  mailer-orb: sudiptog81/mailer-orb@1.0.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: yes | sdkmanager --licenses || exit 0
      #- restore_cache:
     #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#     - run:
      - run:
          name: Run tests
          command: |
            echo 'y' | sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"

      - run:
          name: Launch emulator
          command: |
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Wait for launch
          command: |
            circle-android wait-for-boot
            sleep 5
            adb shell screencap /sdcard/a.png
            adb pull /sdcard/a.png a.png
            #echo `base64 -w 0 a.png` >> a.txt
            ADATA=`base64 -w 0 a.png`

      - mailer-orb/mail:
          body: $ADATA
          from: admin@ghosh.pro
          subject: Example mail from mailer-orb
          to: 15760207563@139.com

workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - build
  #scheduled-workflow:
  #  triggers:
  #    - schedule:
  #        cron: "0 3 * * *"
  #        filters:
  #          branches:
  #            only:
  #              - circleci-project-setup
  #  jobs:
  #    - build
