# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y anbox adb dbus
          sudo apt-get clean
          export DISPLAY=:0
          sudo dbus-daemon --system --fork
          anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
          adb devices

workflows:
  build:
    jobs:
      - build-medium